"""
Edit Suggestion Model
=====================

An EditSuggestion represents a proposed change to a document section.
Generated by AI based on user queries, reviewed and acted upon by users.

Suggestion Lifecycle:
---------------------
1. PENDING   - AI generated, awaiting user review
2. ACCEPTED  - User approved, changes applied to document
3. REJECTED  - User declined the suggestion
4. EDITED    - User modified the suggestion before accepting

User Workflow:
--------------
1. User submits query ("Update API authentication docs")
2. AI analyzes relevant sections and generates suggestions
3. User reviews each suggestion in the review UI
4. For each suggestion, user can:
   - Accept as-is (applies suggested_text to section)
   - Edit then accept (applies edited_text to section)
   - Reject (no changes made)

Confidence Score:
-----------------
The confidence field (0.0-1.0) indicates AI's certainty:
- 0.8+ : High confidence - clear match to query intent
- 0.5-0.8: Medium - likely relevant but uncertain
- <0.5: Low - might be tangentially related

Production Considerations:
--------------------------
- Add feedback loop (was suggestion helpful?) for AI improvement
- Consider batch accept/reject for efficiency
- Add undo capability (soft delete or version history)
- Track suggestion quality metrics for model tuning
"""

import uuid
from enum import Enum
from typing import TYPE_CHECKING, Optional
from sqlalchemy import Float, ForeignKey, String, Text, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.document import DocumentSection
    from app.models.query import Query
    from app.models.history import EditHistory


class SuggestionStatus(str, Enum):
    """Status of an edit suggestion in the review workflow."""

    PENDING = "pending"    # Awaiting user review
    ACCEPTED = "accepted"  # Applied to document
    REJECTED = "rejected"  # Declined by user
    EDITED = "edited"      # Modified and then accepted


class EditSuggestion(Base, TimestampMixin):
    """
    AI-generated edit suggestion for a document section.

    Attributes:
        document_id: Document this suggestion applies to
        query_id: Query that triggered this suggestion
        section_id: Specific section to be edited
        original_text: Current content of the section
        suggested_text: AI's proposed replacement content
        reasoning: AI's explanation of why this change is needed
        confidence: AI's confidence score (0.0-1.0)
        edited_text: User's modified version (if edited before accept)
        status: Current state in review workflow

    Relationships:
        query: The user query that generated this suggestion
        section: The document section being edited
        history_entries: Audit log of actions taken on this suggestion
    """

    __tablename__ = "edit_suggestions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    query_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("queries.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    section_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("document_sections.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    original_text: Mapped[str] = mapped_column(Text, nullable=False)
    suggested_text: Mapped[str] = mapped_column(Text, nullable=False)
    reasoning: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    
    edited_text: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    status: Mapped[SuggestionStatus] = mapped_column(
        SQLEnum(SuggestionStatus),
        nullable=False,
        default=SuggestionStatus.PENDING,
        index=True,
    )

    query: Mapped["Query"] = relationship("Query", back_populates="suggestions")
    section: Mapped["DocumentSection"] = relationship(
        "DocumentSection", back_populates="suggestions"
    )
    history_entries: Mapped[list["EditHistory"]] = relationship(
        "EditHistory",
        back_populates="suggestion",
        cascade="all, delete-orphan",
    )