"""Pydantic schemas for API request/response validation."""

from app.schemas.document import (
    DocumentCreate,
    DocumentListResponse,
    DocumentPreview,
    DocumentPreviewResponse,
    DocumentResponse,
    DocumentSectionCreate,
    DocumentSectionInfo,
    DocumentSectionResponse,
    DocumentUpdate,
    DependencyEdge,
    DependencyGraphResponse,
    DependencyNode,
    ReindexResponse,
    SectionDependenciesResponse,
    SectionDependencyInfo,
    SectionDependencyResponse,
    SectionPreview,
)
from app.schemas.history import (
    HistoryCreate,
    HistoryFilter,
    HistoryListResponse,
    HistoryResponse,
    HistoryStatsResponse,
    UserAction,
)
from app.schemas.query import (
    CompletedEvent,
    ErrorEvent,
    QueryCreate,
    QueryDetailResponse,
    QueryProcessResponse,
    QueryResponse,
    QuerySuggestionListItem,
    SearchProgressEvent,
    StatusUpdateEvent,
    StreamEvent,
    SuggestionGeneratedEvent,
)
from app.schemas.suggestion import (
    BulkSuggestionUpdate,
    SuggestionActionResponse,
    SuggestionApplyRequest,
    SuggestionApplyResponse,
    SuggestionCreate,
    SuggestionResponse,
    SuggestionUpdate,
    SuggestionWithContext,
)

__all__ = [
    # Document
    "DocumentCreate",
    "DocumentListResponse",
    "DocumentPreview",
    "DocumentPreviewResponse",
    "DocumentResponse",
    "DocumentSectionCreate",
    "DocumentSectionInfo",
    "DocumentSectionResponse",
    "DocumentUpdate",
    "DependencyEdge",
    "DependencyGraphResponse",
    "DependencyNode",
    "ReindexResponse",
    "SectionDependenciesResponse",
    "SectionDependencyInfo",
    "SectionDependencyResponse",
    "SectionPreview",
    # History
    "HistoryCreate",
    "HistoryFilter",
    "HistoryListResponse",
    "HistoryResponse",
    "HistoryStatsResponse",
    "UserAction",
    # Query
    "CompletedEvent",
    "ErrorEvent",
    "QueryCreate",
    "QueryDetailResponse",
    "QueryProcessResponse",
    "QueryResponse",
    "QuerySuggestionListItem",
    "SearchProgressEvent",
    "StatusUpdateEvent",
    "StreamEvent",
    "SuggestionGeneratedEvent",
    # Suggestion
    "BulkSuggestionUpdate",
    "SuggestionActionResponse",
    "SuggestionApplyRequest",
    "SuggestionApplyResponse",
    "SuggestionCreate",
    "SuggestionResponse",
    "SuggestionUpdate",
    "SuggestionWithContext",
]